name: AIgogo iOS Build
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install --repo-update || echo ""No Podfile, skipping""
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    - name: Build IPA
      run: |
        mkdir -p build
        if [ -f ""Aigogo.xcworkspace"" ]; then
          xcodebuild -workspace Aigogo.xcworkspace -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath \C:\Aigogo/build/AIgogo.xcarchive
        else
          xcodebuild -project Aigogo.xcodeproj -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath \C:\Aigogo/build/AIgogo.xcarchive
        fi
        xcodebuild -exportArchive -archivePath \C:\Aigogo/build/AIgogo.xcarchive -exportOptionsPlist exportOptions.plist -exportPath \C:\Aigogo/build
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: AIgogo.ipa
        path: \C:\Aigogo/build/AIgogo.ipa
