name: Aigogo iOS Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        if [ -f Podfile ]; then
          pod install --repo-update
        fi
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    - name: Build IPA
      run: |
        if [ ! -f Aigogo.xcworkspace ]; then
          echo 'Podfile 확인 후 pod install 필요, xcworkspace 자동 생성'
          exit 66
        fi
        mkdir -p build
        xcodebuild -workspace Aigogo.xcworkspace -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath \C:\Aigogo/build/AIgogo.xcarchive
        xcodebuild -exportArchive -archivePath \C:\Aigogo/build/AIgogo.xcarchive -exportOptionsPlist exportOptions.plist -exportPath \C:\Aigogo/build
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: AIgogo.ipa
        path: \C:\Aigogo/build/AIgogo.ipa
