name: AIgogo iOS Build
on:
  push:
    branches: [main]

concurrency:
  group: AIgogo-iOS-Build
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Install CocoaPods
      run: gem install cocoapods

    - name: Install Pods
      run: pod install --repo-update

    - name: Build IPA
      run: |
        mkdir -p build
        if [ -f Aigogo.xcworkspace ]; then
          xcodebuild -workspace Aigogo.xcworkspace -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath ./build/AIgogo.xcarchive
        else
          xcodebuild -project Aigogo.xcodeproj -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath ./build/AIgogo.xcarchive
        fi
        if [ ! -f exportOptions.plist ]; then
          exit 66
        fi
        xcodebuild -exportArchive -archivePath ./build/AIgogo.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./build

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: AIgogo.ipa
        path: ./build/AIgogo.ipa
