name: Aigogo iOS Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
    - name: Build IPA
      run: |
        mkdir -p build
        # Podfile이 있으면 pod install
        if [ -f Podfile ]; then
          pod install --repo-update
        fi
        # xcworkspace or xcodeproj로 빌드
        if [ -f Aigogo.xcworkspace ]; then
          xcodebuild -workspace Aigogo.xcworkspace -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath \C:\Aigogo/build/AIgogo.xcarchive
        elif [ -f Aigogo.xcodeproj ]; then
          xcodebuild -project Aigogo.xcodeproj -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath \C:\Aigogo/build/AIgogo.xcarchive
        else
          echo ""❌ Aigogo.xcworkspace / Aigogo.xcodeproj 둘 다 없음, 빌드 불가""
          exit 1
        fi
        xcodebuild -exportArchive -archivePath \C:\Aigogo/build/AIgogo.xcarchive -exportOptionsPlist exportOptions.plist -exportPath \C:\Aigogo/build
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: AIgogo.ipa
        path: \C:\Aigogo/build/AIgogo.ipa
