name: AIgogo iOS Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Ensure Podfile and Workspace
        run: |
          if [ ! -f Podfile ]; then
            echo 'Podfile 없음, 기본 생성'
            cat <<EOF > Podfile
platform :ios, '15.0'
use_frameworks!
target 'AIgogo' do
  # 필요한 Pods 삽입
end
EOF
          fi

          if [ ! -f Aigogo.xcworkspace ]; then
            echo '워크스페이스 없음, pod install 실행하여 생성'
            sudo gem install cocoapods
            pod install --repo-update
          fi

          if [ ! -f Aigogo.xcworkspace ] && [ ! -f Aigogo.xcodeproj ]; then
            echo '❌ Aigogo.xcworkspace / Aigogo.xcodeproj 둘 다 존재하지 않습니다. 빌드 불가'
            exit 66
          fi

      - name: Build IPA
        run: |
          mkdir -p build
          if [ -f Aigogo.xcworkspace ]; then
            xcodebuild -workspace Aigogo.xcworkspace -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath \C:\Aigogo/build/AIgogo.xcarchive
          else
            xcodebuild -project Aigogo.xcodeproj -scheme AIgogo -sdk iphoneos -configuration Release archive -archivePath \C:\Aigogo/build/AIgogo.xcarchive
          fi

          if [ ! -f exportOptions.plist ]; then
            echo '❌ exportOptions.plist가 없습니다. IPA 추출 불가'
            exit 66
          fi
          xcodebuild -exportArchive -archivePath \C:\Aigogo/build/AIgogo.xcarchive -exportOptionsPlist exportOptions.plist -exportPath \C:\Aigogo/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: AIgogo.ipa
          path: \C:\Aigogo/build/AIgogo.ipa
